app:
  name: ACE-FRONT
  description: ${app.name} is a Spring Boot application


spring:
    resources:
      staticLocations: classpath:/static/, classpath:/assets/   #ResourceProperties.java
    mvc:
      dateFormat: yyyy-MM-dd
    thymeleaf:
      cache: false
      mode: html
      prefix: classpath:/templates/



server:
  port: 8002
  sessionTimeout: 30
  contextPath: /



site:
  version: 1.0,
  author: xiaochenlong



