app:
  name: ACE-ADMIN
  description: ${app.name} is a Spring Boot application


spring:
    resources:
      staticLocations: classpath:/static/, classpath:/assets/   #ResourceProperties.java
    mvc:
      dateFormat: yyyy-MM-dd
    thymeleaf:
      cache: false
      mode: html
      prefix: classpath:/templates/
    datasource:
          name: ace
          url: jdbc:mysql://192.168.99.100:3306/ace
          username: root
          password: toor
          type: org.apache.tomcat.jdbc.pool.DataSource
          #type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          filters: stat
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select current_timestamp()
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20


#MybatisProperties
mybatis:
    mapperLocations: classpath:/mapper/*.xml

security:
  basic:
    enabled: false

server:
  port: 8001
  sessionTimeout: 30
  contextPath: /



site:
  version: 1.0,
  author: xiaochenlong



